{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = VERSION %}
{% set project = pyproject['project'] %}

package:
  name: learn-jax
  version: {{ version }}

# contra copilot there is no way to include/exclude certain files / directories
source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -vv .
  noarch: python
  number: 0

requirements:
  host:
    - python {{ project['requires-python'] }}
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python {{ project['requires-python'] }}
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - learn_jax
  source_files:
    - tests
  requires:
    {% for dep in project['optional-dependencies']['test'] %}
    - {{ dep.lower() }}
    {% endfor %}
  commands:
    - pytest

about:
  home: https://github.com/jonmoore/learn-jax
  summary: Materials for learning JAX
  license: {{ pyproject.get('license') }}
  license_file: LICENSE
